Update backend.yml

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -1,28 +1,81 @@
-- name: Check required secrets
-  env:
-    SERVER_HOST: ${{ secrets.SERVER_HOST }}
-    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-    DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
-    JWT_SECRET: ${{ secrets.JWT_SECRET }}
-  run: |
-    if [ -z "$SERVER_HOST" ]; then
-      echo "ERROR: SERVER_HOST is empty"
-      exit 1
-    fi
+name: Backend CI/CD
 
-    if [ -z "$SSH_PRIVATE_KEY" ]; then
-      echo "ERROR: SSH_PRIVATE_KEY is empty"
-      exit 1
-    fi
+on:
+  workflow_dispatch:
 
-    if [ -z "$DB_PASSWORD" ]; then
-      echo "ERROR: DB_PASSWORD is empty"
-      exit 1
-    fi
+jobs:
+  build-push-deploy:
+    runs-on: ubuntu-latest
 
-    if [ -z "$JWT_SECRET" ]; then
-      echo "ERROR: JWT_SECRET is empty"
-      exit 1
-    fi
+    steps:
 
-    echo "All required secrets are available."
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: Build Docker image
+        run: |
+          docker build -t kanavenavamshi/backend:latest ./backend
+
+      - name: Push Docker image
+        run: |
+          docker push kanavenavamshi/backend:latest
+
+      - name: Check required secrets
+        env:
+          SERVER_HOST: ${{ secrets.SERVER_HOST }}
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
+          JWT_SECRET: ${{ secrets.JWT_SECRET }}
+        run: |
+          if [ -z "$SERVER_HOST" ]; then
+            echo "ERROR: SERVER_HOST is empty"
+            exit 1
+          fi
+
+          if [ -z "$SSH_PRIVATE_KEY" ]; then
+            echo "ERROR: SSH_PRIVATE_KEY is empty"
+            exit 1
+          fi
+
+          if [ -z "$DB_PASSWORD" ]; then
+            echo "ERROR: DB_PASSWORD is empty"
+            exit 1
+          fi
+
+          if [ -z "$JWT_SECRET" ]; then
+            echo "ERROR: JWT_SECRET is empty"
+            exit 1
+          fi
+
+          echo "All required secrets are available."
+
+      - name: Deploy to EC2
+        uses: appleboy/ssh-action@v1.2.0
+        with:
+          host: ${{ secrets.SERVER_HOST }}
+          username: ec2-user
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          port: 22
+          script: |
+            docker pull kanavenavamshi/backend:latest
+
+            docker stop backend || true
+            docker rm backend || true
+
+            docker run -d \
+              --name backend \
+              -p 8089:8080 \
+              -e DB_HOST=books-rds.cux0w262wytu.us-east-1.rds.amazonaws.com \
+              -e PORT=3306 \
+              -e DB_USER=admin \
+              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
+              -e DB_NAME=booksapp \
+              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
+              -e JWT_EXPIRES_IN=7d \
+              kanavenavamshi/backend:latest
